### ISSUE TITLE
OpenStack cli" fails with "service 'org.kde.klipper' does not exist." error on Fedora 34

### ISSUE THREAD

**Issue by scottmarlow** [asweigart/pyperclip#202]
I have the default Fedora 34 installation (GNOME) and also have KDE installed as well.  When I try to use the [OpenStack client ](https://docs.openstack.org/python-openstackclient) I get the following failure:

> openstack server list
> Service 'org.kde.klipper' does not exist.
> Traceback (most recent call last):
>   File "/usr/bin/openstack", line 6, in <module>
>     from openstackclient.shell import main
>   File "/usr/lib/python3.9/site-packages/openstackclient/shell.py", line 24, in <module>
>     from osc_lib import shell
>   File "/usr/lib/python3.9/site-packages/osc_lib/shell.py", line 24, in <module>
>     from cliff import app
>   File "/usr/lib/python3.9/site-packages/cliff/app.py", line 22, in <module>
>     import cmd2
>   File "/usr/lib/python3.9/site-packages/cmd2/__init__.py", line 30, in <module>
>     from .cmd2 import Cmd
>   File "/usr/lib/python3.9/site-packages/cmd2/cmd2.py", line 48, in <module>
>     from .clipboard import can_clip, get_paste_buffer, write_to_paste_buffer
>   File "/usr/lib/python3.9/site-packages/cmd2/clipboard.py", line 12, in <module>
>     _ = pyperclip.paste()
>   File "/usr/lib/python3.9/site-packages/pyperclip/__init__.py", line 640, in lazy_load_stub_paste
>     return paste()
>   File "/usr/lib/python3.9/site-packages/pyperclip/__init__.py", line 268, in paste_klipper
>     assert len(clipboardContents) > 0
> AssertionError
> 

Could someone please clarify if the ^ failure is caused by `klipper` or something else?  

The only workaround that I found is to remove KDE (5) desktop + other KDE things via `dnf remove *kde*` which solved the failure.  

I will soon try the other workaround mentioned on https://github.com/asweigart/pyperclip/issues/26#issuecomment-152657920 of starting `klipper` (after I install KDE 5 desktop again).  

Is the https://github.com/asweigart/pyperclip/issues/26 issue enough to track fixing this issue for KDE 6 or do we need an additional issue created elsewhere for fixing the `service 'org.kde.klipper' does not exist` failure?

**Comment by tosky** [comment]
For the record, it's not about Plasma (klipper is part of Plasma): the component which handles the clipboard changed long ago, the fix needs to happen in pyperclib. That's probably why #26 is still open.

**Comment by scottmarlow** [comment]
> For the record, it's not about Plasma (klipper is part of Plasma): the component which handles the clipboard changed long ago, the fix needs to happen in pyperclib. That's probably why #26 is still open.

Perhaps we should close https://github.com/asweigart/pyperclip/issues/202 as a duplicate after we finish discussing it.


> Also for the record, I'm running openstackclient on top of fedora with KDE and it works fine.
> 
> Probably lack of running dbus service while having something installed by kde packages triggers this behaviour?

Currently, I just know that removing the *kde* components helped.  I do still have various k* components (I use `konsole` every day and don't have the failure just from having `konsole` installed).

I'm currently on a few different critical paths but will hopefully be able to experiment more to better isolate the issue (e.g. install KDE desktop again and recreate the issue and then try workaround of starting `klipper`).

**Comment by michelamarie** [comment]
In case it may be helpful for others who run into this problem, @scottmarlow's solution did not work for me, but removing the Openstack CLI packages did the trick.

It appears that this issue happens when users install the OpenStack CLI packages in Fedora while running KDE Plasma, but then try to invoke the CLI tools later while running Gnome in Fedora _(at least in versions 34 - 36)_. 

So, if you run into this situation, and you would like to continue running the OpenStack CLI tools in Gnome, do the following:
* Remove the OpenStack CLI packages: `sudo dnf remove python3-openstackclient python3-novaclient python3-cinderclient python3-swiftclient`. Try doing this with DNF first, or with pip, if that is how you installed the OpenStack stuff. Please note that the RPMs appear to be a wrapper for installing the CLI tools via pip. Uninstalling the RPMs will remove everything related to the OpenStack CLI tools, but the same is not true if you only remove them via pip if they were installed with dnf / yum in the first place.
* Install the OpenStack CLI packages again: `sudo dnf install python3-openstackclient python3-novaclient python3-cinderclient python3-swiftclient`
* Invoke your OpenStack source file to load your OpenStack environment variables (to authenticate to your OpenStack environment and such).

That solved the issue for me!

Hopefully, some sort of change can be made such that this issue does not happen at all, but until then, there are work-arounds.
