### ISSUE TITLE
Trying to copy output of os.urandom() causes UnicodeDecodeError

### ISSUE THREAD

**Issue by zevav** [asweigart/pyperclip#22]
`pyperclip.copy(os.urandom(24))`

`UnicodeDecodeError: 'ascii' codec can't decode byte 0x93 in position 1: ordinal not in range(128)`

**Comment by luckydonald** [comment]
Is urandom ascii? I a afraid not.

**Comment by asweigart** [comment]
On Python 3, os.urandom() returns a bytes value, not a string. So you'd have to decode it to a string using some encoding. However, this doesn't make sense because you're bound to have un-decodable values no matter what encoding you use. For a good explanation about just what bytes and strings are at a conception level, I recommend this talk by Ned Batchelder: http://nedbatchelder.com/text/unipain.html

On Python 2, os.urandom() returns a string, so pyperclip.copy() should work.

If you want to just have a random string, I'd recommend some code like:

    import string, random
    chars = string.digits + string.ascii_letters
    ''.join([random.choice(chars) for i in range(24)])
