### ISSUE TITLE
Please don't throw exceptions during import.

### ISSUE THREAD

**Issue by jonathanslenders** [asweigart/pyperclip#23]
Hi,
``import pyperclip`` should never throw an exception. Currently it raises an exception of type ``Exception`` or a ``RuntimeError`` on some systems.

Instead it's better to have the copy/paste functions raise an exception when it's called, if the platform is not supported. (But that should be a ``PyperclipException`` or something similar. Not ``Exception``.)
Maybe we could also add another function ``platform_is_supported`` for checking.

See also: http://chrismorgan.info/blog/say-no-to-import-side-effects-in-python.html

Is this a change to which you are open, or should I fork? I'm willing to create a pull request.

Jonathan

**Comment by mhils** [comment]
I second this.
```python
try:
    import pyperclip
except:
    pyperclip = False
```
is a fairly ugly workaround.

**Comment by asweigart** [comment]
Yes, I agree. Fixed in 1e0d63c0d84b18890c9d2146bd5ebea28952b74f

Sorry for taking so long to work through this list. I've rearranged the code so that instead of throwing an exception when pyperclip is imported, it sets the copy() & paste() functions to _noCopy() and _noPaste(), which when called will raise a NotImplementedError exception. (And provides info on where to look for how to solve this.)

Again, sorry for the delay. I've added you to the AUTHORS.txt, thanks for contributing!

**Comment by mhils** [comment]
Thanks for the now super quick turnaround! :relaxed: 
I don't want to be too picky, but raising RuntimeError or OSError seems more appropriate. NotImplementedError fulfills a different purpose:

NotImplementedError
> This exception is derived from RuntimeError. In user defined base classes, abstract methods should raise this exception when they require derived classes to override the method.

Thoughts?

**Comment by asweigart** [comment]
Good point, I'll switch this to RuntimeError.
